name = "benny-pick"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-03"

# D1 데이터베이스 연결
[[d1_databases]]
binding = "DB"
database_name = "benny-pick"
database_id = "ba966c1e-c86f-45aa-974e-c2e2310334bd"

# Workers AI 연결 (필수)
[ai]
binding = "AI"